name: Ci Workflows

on: [push, pull_request]

jobs:
  lint:
    name: Lint codebase (& format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: ./.github/actions/_setup-node
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint:fix
  
  check-types:
    name: Check typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: ./.github/actions/_setup-node
      - name: Install
        run: npm install
      - name: Check types
        run: npm run check-types

  build-typescript:
    name: Build typescript
    needs: [check-types]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: ./.github/actions/_setup-node
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: ./.github/actions/_setup-node
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test:unit

  run-integration-tests:
    name: Integration tests
    needs: [run-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: ./.github/actions/_setup-node
      - name: Install
        run: npm install
      - name: Run tests
        run: npm run test:integration